### PR TITLE
remotewrite: Small refactor of directories.

### PR DESCRIPTION
**Pull request by bwplotka**
In prep for adding v2 compliance support, some tiny clean up of dirs.

### CODE REVIEW

**Comment by bwplotka** [comment]
Uu, sounds like this needs a total move to GH actions.

**Comment by juliusv** [comment]
@bwplotka Ouff, I have no idea about GH actions and our current build system details 🙈

**Comment by bwplotka** [comment]
image

**Comment by bwplotka** [comment]
(CI is fixed)

**Comment by juliusv** [comment]
:+1:

**Review by juliusv — APPROVED** [review]

**Pull request merged**
